name: sicix
description: Developer for Sicix Mobile App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  infrastructure:
    path: external_library/infrastructure
  data_infrastructure:
    path: external_library/infrastructure/data
  ui_api:
    path: external_library/ui_api

  cupertino_icons: ^1.0.2
  filter_list: ^1.0.2
  intl: ^0.17.0

  get: ^4.6.5
  rxdart: ^0.27.5 
  path_provider: ^2.0.11

  permission_handler: ^10.0.0
  flutter_typeahead: ^4.1.1
  faker: ^2.0.0
  multi_select_flutter: ^4.1.3
  flutter_switch: ^0.3.2

  # Local data
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.6
  json_annotation: ^4.5.0

  # Firebase
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^9.7.0

  geolocator: ^9.0.2
  geocoding: ^2.0.5

  connectivity_plus: ^2.3.6+1
  url_launcher: ^6.0.9 
  flutter_html: 3.0.0-alpha.5 
  flutter_html_all: 3.0.0-alpha.5
  flutter_widget_from_html: ^0.8.5
  chewie: ^1.3.4 

  qr_code_scanner: ^1.0.1
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  extended_image: ^6.0.2+1
  image_picker: ^0.8.5+3
  photo_manager: 2.1.4
  image_crop: ^0.4.1
  file_picker: ^5.0.1
  flutter_image_compress: ^1.1.0
  photo_view: ^0.14.0
  image_downloader: ^0.31.0

  package_info_plus: ^1.4.2
  device_info_plus: ^4.1.0   
  google_fonts: ^3.0.1
  uuid: ^3.0.6
  date_format: ^2.0.6
  keyboard_dismisser: ^3.0.0 
  jwt_decoder: ^2.0.1

  web_socket_channel: ^2.2.0
  dash_chat_2: ^0.0.14
  flutter_easyloading: ^3.0.0 
  dropdown_button2: ^1.9.0

  carousel_slider: ^4.1.1
  flutter_custom_dialog: ^1.2.0
  timeago: ^3.2.2
  percent_indicator: ^4.2.2
  modal_bottom_sheet: ^2.1.0
  pull_to_refresh_flutter3: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1 
  scrollable_positioned_list: ^0.3.2
  badges: ^2.0.3
  expandable: ^5.0.1
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.3.0
  persistent_bottom_nav_bar: ^5.0.2
  infinite_scroll_pagination: ^3.2.0
  sliding_up_panel: ^2.0.0+1
  multiselect: ^0.0.7
  flutter_slidable: ^2.0.0
  syncfusion_flutter_calendar: ^20.3.45
  flutter_neat_and_clean_calendar: ^0.3.9+23
  tiengviet: ^0.5.0 

  status_change:
    git:
      url: https://github.com/usamaaelgendy/status_change.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/resource/assets_resources/icons/
    - lib/resource/assets_resources/icons/tabbar/
    - lib/resource/assets_resources/icons/setting/
    - lib/resource/assets_resources/icons/reaction/
    - lib/resource/assets_resources/icons/messenger/
    - lib/resource/assets_resources/icons/notification/
    - lib/resource/assets_resources/icons/file/
    - lib/resource/assets_resources/images/ 
    - lib/resource/assets_resources/images/theme/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
