// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEn-jb4lB9GYAXHb1ddWZEzsVU1LDHR4s',
    appId: '1:928761491421:android:935d5df489534093401034',
    messagingSenderId: '928761491421',
    projectId: 'sicix-88a3f',
    storageBucket: 'sicix-88a3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5MrOK8NvR-Bg6U8W9CFc55hzyrR_JOLM',
    appId: '1:928761491421:ios:d0629dca4ee0e420401034',
    messagingSenderId: '928761491421',
    projectId: 'sicix-88a3f',
    storageBucket: 'sicix-88a3f.appspot.com',
    iosClientId:
        '928761491421-i9h19rup1prrb27erh177ahhmh4rgd9b.apps.googleusercontent.com',
    iosBundleId: 'com.ngsc.sicix',
  );
}
