const MESSAGE_UNAUTHORIZED = 'MESSAGE_UNAUTHORIZED';
const MESSAGE_SERVICE_UPGRADING = 'MESSAGE_SERVICE_UPGRADING';

const POST_DETAIL = 'POST_DETAIL';
const IS_COMMENT = 'IS_COMMENT';

const CONVERSATION_ARGUMENT = 'CONVERSATION_ARGUMENT';
const PIN_GROUP_ARGUMENT = 'PIN_GROUP_ARGUMENT';
const PIN_PRIVATE_ARGUMENT = 'PIN_PRIVATE_ARGUMENT';

const NAME_ARGUMENT = 'NAME_ARGUMENT';
const IMAGE_ARGUMENT = 'IMAGE_ARGUMENT';

const COUNTRY_ID = 'COUNTRY_ID';
const PROVINCE_ID = 'PROVINCE_ID';
const DISTRICT_ID = 'DISTRICT_ID';
const WARD_ID = 'WARD_ID';
const AUTHORIZATION_GROUP_ID = 'AUTHORIZATION_GROUP_ID';
const CONTACT_ID = 'CONTACT_ID';
const PRODUCT_ID = 'PRODUCT_ID';
const ACCOUNT_ID = 'ACCOUNT_ID';
const ADDRESS_ID = 'ADDRESS_ID';
const ACCOUNT_DOCUMENT_ID = 'ACCOUNT_DOCUMENT_ID';

const IS_MULTI_SELECT = 'IS_MULTI_SELECT';
const LIST_SELECTED = 'LIST_SELECTED';

const LEAD_MODEL = 'LEAD_MODEL';
const LEAD_DETAIL = 'LEAD_DETAIL';
const LEAD_CONVERT_REQUEST = 'LEAD_CONVERT_REQUEST';

const ACCOUNT_INFO = 'ACCOUNT_INFO';
const CONTACT_INFO = 'CONTACT_INFO';
const PRODUCT_LIST = 'PRODUCT_LIST';
const ACCOUNT_LIST = 'ACCOUNT_LIST';

const OPPORTUNITY_INFO = 'OPPORTUNITY_INFO';

//người liên hệ
const CONTACT_ADDRESS_TYPE = 'CONTACT_ADDRESS_TYPE';

//nhân sự liên quan
const PARTY_INVOLVED = 'PARTY_INVOLVED';
const PARTY_INVOLVED_TYPE = 'PARTY_INVOLVED_TYPE';

//Mối quan hệ liên quan
const ACCOUNT_CONTACT = 'ACCOUNT_CONTACT';
const OBJECT_TYPE = 'OBJECT_TYPE';
